config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/galaxyproject/galaxy:
      branch: dev
      repo: https://github.com/galaxyproject/galaxy
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/galaxyproject/galaxy git:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-purple-termite.sh
        container: qc.acc_sleepy-bistre-barb
  QC.Doc:
    repos:
      github.com/galaxyproject/galaxy find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-aquamarine-earwig.sh
        container: qc.doc_squirrely-eggplant-millipede
      github.com/galaxyproject/galaxy git:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-olive-argentino.sh
        container: qc.doc_hazy-harlequin-chihuahua
      github.com/galaxyproject/galaxy markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-corn-pig.sh
        container: qc.doc_flimsy-corn-orangutan
      github.com/galaxyproject/galaxy restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-ruby-fowl.sh
        container: qc.doc_wheezy-saffron-chinchilla
  QC.Lic:
    repos:
      github.com/galaxyproject/galaxy licensee:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-xanthic-albatross.sh
        container: qc.lic_flabby-crimson-yak
  QC.Sec:
    repos:
      github.com/galaxyproject/galaxy bandit:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-flax-heron.sh
        container: qc.sec_slaphappy-champagne-peccary
  QC.Sty:
    repos:
      github.com/galaxyproject/galaxy flake8:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-magnolia-newfoundland.sh
        container: qc.sty_wiggy-ruby-anteater
      github.com/galaxyproject/galaxy hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-puce-dingo.sh
        container: qc.sty_wiggy-beige-mandrill
      github.com/galaxyproject/galaxy jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-orange-mandrill.sh
        container: qc.sty_paltry-rust-akbash
  QC.Uni:
    repos:
      github.com/galaxyproject/galaxy pytest:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-carmine-budgerigar.sh
        container: qc.uni_squirrely-taupe-dormouse
  QC.Ver:
    repos:
      github.com/galaxyproject/galaxy get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-amethyst-bat.sh
        container: qc.ver_hazy-firebrick-fly
timeout: 5400
